### ISSUE TITLE
cp: cannot stat 'example/src/*.{html,mp3}': No such file or directory

### ISSUE THREAD

**Issue by markidm** [jamesseanwright/wax#1]
Running `npm run dev`, I get the error which is in the title, and this in my log:
```

0 info it worked if it ends with ok
1 verbose cli [ '/home/moox/.nvm/versions/node/v8.11.4/bin/node',
1 verbose cli   '/home/moox/.nvm/versions/node/v8.11.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle wax-core@0.1.1~predev: wax-core@0.1.1
6 info lifecycle wax-core@0.1.1~dev: wax-core@0.1.1
7 verbose lifecycle wax-core@0.1.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle wax-core@0.1.1~dev: PATH: /home/moox/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/d/Developer/React/wax/node_modules/.bin:/home/moox/.local/bin:/home/moox/.yarn/bin:/home/moox/.config/yarn/global/node_modules/.bin:/home/moox/.nvm/versions/node/v8.11.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/ProgramData/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Intel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files (x86)/QuickTime/QTSystem:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Python34/Scripts:/mnt/c/Python34:/mnt/c/Program Files/Amazon/AWSCLI:/mnt/c/Users/Mark/AppData/Roaming/npm:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/GitExtensions:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/HashiCorp/Vagrant/bin:/mnt/c/PHP7:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Ruby23-x64/bin:/mnt/c/Program Files/nodejs:/mnt/c/Users/Mark/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Intel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Users/Mark/AppData/Roaming/npm:/mnt/c/Users/Mark/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/PostgreSQL/10/bin:/mnt/c/Users/Mark/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
9 verbose lifecycle wax-core@0.1.1~dev: CWD: /mnt/d/Developer/React/wax
10 silly lifecycle wax-core@0.1.1~dev: Args: [ '-c',
10 silly lifecycle   'npm run build && npm run build-example && node example/devServer' ]
11 silly lifecycle wax-core@0.1.1~dev: Returned: code: 1  signal: null
12 info lifecycle wax-core@0.1.1~dev: Failed to exec dev script
13 verbose stack Error: wax-core@0.1.1 dev: `npm run build && npm run build-example && node example/devServer`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/moox/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/moox/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wax-core@0.1.1
15 verbose cwd /mnt/d/Developer/React/wax
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/home/moox/.nvm/versions/node/v8.11.4/bin/node" "/home/moox/.nvm/versions/node/v8.11.4/bin/npm" "run" "dev"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error wax-core@0.1.1 dev: `npm run build && npm run build-example && node example/devServer`
22 error Exit status 1
23 error Failed at the wax-core@0.1.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
I am using Ubuntu on Windows.

**Comment by jamesseanwright** [comment]
Hey! 👋

Thanks for raising this; I mainly work on my employer's MacBook, but previously used Ubuntu heavily and have encountered similar issues before; I think there are discrepancies with how their respective shells interpret globs.

I'll resolve this tomorrow.

**Comment by jamesseanwright** [comment]
@markidm It turns out that it's an interop issue between npm and Dash, the default shell of Ubuntu. I've thus updated this part of the script to be interpreted by Bash and can confirm this works across Ubuntu and macOS. Please can you update your clone and try again?

**Comment by jamesseanwright** [comment]
I'm going to close this for now, but please let me know if you encounter further quirks surrounding this issue.
